/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbastecimentosRouteImport } from './routes/abastecimentos'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as ManutencoesRouteImport } from './routes/manutencoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentosRoute = AbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencoesRoute = ManutencoesRouteImport.update({
  id: '/manutencoes',
  path: '/manutencoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/frota': typeof FrotaRoute
  '/manutencoes': typeof ManutencoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/frota': typeof FrotaRoute
  '/manutencoes': typeof ManutencoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/frota': typeof FrotaRoute
  '/manutencoes': typeof ManutencoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abastecimentos' | '/frota' | '/manutencoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abastecimentos' | '/frota' | '/manutencoes'
  id: '__root__' | '/' | '/abastecimentos' | '/frota' | '/manutencoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentosRoute: typeof AbastecimentosRoute
  FrotaRoute: typeof FrotaRoute
  ManutencoesRoute: typeof ManutencoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimentos': {
      id: '/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AbastecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencoes': {
      id: '/manutencoes'
      path: '/manutencoes'
      fullPath: '/manutencoes'
      preLoaderRoute: typeof ManutencoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentosRoute: AbastecimentosRoute,
  FrotaRoute: FrotaRoute,
  ManutencoesRoute: ManutencoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
